[project]
name = "energiepreis-vattenfall-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "icecream>=2.2.0",
    "matplotlib>=3.10.9",
    "mcp[cli]>=2.0.0",
    "ollama>=0.6.2",
    "paho-mqtt>=2.1.0",
    "python-dotenv>=1.0.1",
    "requests>=2.33.1",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]

[project.scripts]
start = "main"
